CREATE DATABASE SP_MEDIC_GROUP_DEV_MANHA

USE SP_MEDIC_GROUP_DEV_MANHA

-- TABELA QUE DIZ SE O USUARIO E MEDICO OU PACIENTE

CREATE TABLE TIPO_USUARIO (
ID INT IDENTITY PRIMARY KEY
, NOME VARCHAR (250) NOT NULL 
);

--TABELA QUE SALVA OS DADOS DO USUARIO

CREATE TABLE USUARIO (
ID INT IDENTITY PRIMARY KEY NOT NULL
,ID_TIPO INT FOREIGN KEY REFERENCES TIPO_USUARIO (ID) NOT NULL
, EMAIL VARCHAR (250) NOT NULL 
, SENHA VARCHAR (250) NOT NULL 
);

-- TABELA PARA SALVAR TODAS AS ESPECIFICAÇÕES PROFISSIONAIS DA CLINICA

CREATE TABLE ESPECIALIZACAO (
ID INT IDENTITY PRIMARY KEY NOT NULL
, NOME VARCHAR (250) NOT NULL 
);

-- TABELA PARA SALVAR OS DADOS DO MEDICO

CREATE TABLE MEDICO (
ID_USUARIOS INT FOREIGN KEY REFERENCES USUARIO (ID) NOT NULL
,CRM CHAR (7) NOT NULL 
, NOME VARCHAR (250) NOT NULL 
, ID_ESPECIALIZACAO INT FOREIGN KEY REFERENCES ESPECIALIZACAO (ID) NOT NULL
,ID_CLINICA INT FOREIGN KEY REFERENCES CLINICA (ID) NOT NULL
);

-- TABELA PARA SALVAR OS DADOS PESSOAIS DO PACIENTE

CREATE TABLE PRONTUARIO (
ID_USUARIOS INT FOREIGN KEY REFERENCES USUARIO (ID) NOT NULL
 ,NOME VARCHAR (250) NOT NULL 
, RG CHAR (12) NOT NULL 
, CPF CHAR (14) NOT NULL 
, ENDEREÇO VARCHAR (250) NOT NULL 
, DATA_NASCIMENTO DATE 
,TELEFONE CHAR (11) NOT NULL 
);

-- TABELA PARA SALVAR AS CONSULTAS 

CREATE TABLE CONSULTA (
ID INT IDENTITY PRIMARY KEY NOT NULL
,ID_PRONTUARIOS INT FOREIGN KEY REFERENCES USUARIO (ID) NOT NULL
,ID_MEDICOS INT FOREIGN KEY REFERENCES USUARIO (ID) NOT NULL
,ID_STATUS INT FOREIGN KEY REFERENCES STATUS_CONSULTA (ID) NOT NULL
, DATA_CONSULTA DATETIME NOT NULL
, DESCRICAO VARCHAR (300) NOT NULL
);

-- TABELA QUE DIZ SE A CONSULTA ESTA MARCADA OU  DESMARCADA

CREATE TABLE STATUS_CONSULTA (
ID INT IDENTITY PRIMARY KEY
,NOME VARCHAR (250)
);

CREATE TABLE CLINICA (
ID INT IDENTITY PRIMARY KEY
,NOME VARCHAR (100)
,CNPJ CHAR (14) NOT NULL 
,RAZAO_SOCIAL VARCHAR (100) NOT NULL
,ENDERECO VARCHAR (200) NOT NULL
);


